In [37]:
import torch
import torch.utils.data as Data
import random
import numpy as np
import torch.nn as nn
from torch.nn import init
import torch.optim as optim

In [57]:
#模拟数据
num_inputs = 2
num_examples = 1000
true_w = [2, -3.4]
true_b = 4.2
features = torch.tensor(np.random.normal(0, 1, (num_examples, num_inputs)), dtype=torch.float)
labels = true_w[0] * features[:, 0] + true_w[1] * features[:, 1] + true_b
labels += torch.tensor(np.random.normal(0, 0.01, size=labels.size()), dtype=torch.float)
print(labels.shape)

torch.Size([1000])


In [58]:
batch_size = 10

torch_data = Data.TensorDataset(features, labels)

dataset = Data.DataLoader(torch_data, batch_size, shuffle=True)


In [60]:
class LinearNet(nn.Module):
    def __init__(self):
        super(LinearNet, self).__init__()
        self.l1 = nn.Linear(2,1)
        
    def forward(self, x):
        out = self.l1(x)
        return out
    
net = LinearNet()

init.normal_(net.l1.weight, mean=0, std=0.01)
init.constant_(net.l1.bias, val=0)

Parameter containing:
tensor([0.], requires_grad=True)

In [61]:
loss_func = nn.MSELoss()
optimizer = optim.SGD(net.parameters(), lr=0.03)
print(optimizer)

SGD (
Parameter Group 0
    dampening: 0
    lr: 0.03
    momentum: 0
    nesterov: False
    weight_decay: 0
)


In [62]:
EPOCH = 3
for epoch in range(EPOCH):
    for step, (batch_x, batch_y) in enumerate(dataset):
        output = net(batch_x)
        loss = loss_func(output, batch_y.view(batch_y.size(0), 1))
        optimizer.zero_grad()
        loss.backward()
        optimizer.step()
        
        if step % 20 == 0:
            print('epoch:', epoch, '|step:', step, '|loss:', loss.data)
    print('epoch %d, loss: %f' % (epoch, loss.item()))

epoch: 0 |step: 0 |loss: tensor(56.5056)
epoch: 0 |step: 20 |loss: tensor(2.4671)
epoch: 0 |step: 40 |loss: tensor(0.2342)
epoch: 0 |step: 60 |loss: tensor(0.0203)
epoch: 0 |step: 80 |loss: tensor(0.0008)
epoch 0, loss: 0.000089
epoch: 1 |step: 0 |loss: tensor(0.0002)
epoch: 1 |step: 20 |loss: tensor(0.0001)
epoch: 1 |step: 40 |loss: tensor(8.1444e-05)
epoch: 1 |step: 60 |loss: tensor(0.0001)
epoch: 1 |step: 80 |loss: tensor(8.6230e-05)
epoch 1, loss: 0.000076
epoch: 2 |step: 0 |loss: tensor(0.0001)
epoch: 2 |step: 20 |loss: tensor(0.0002)
epoch: 2 |step: 40 |loss: tensor(0.0002)
epoch: 2 |step: 60 |loss: tensor(0.0002)
epoch: 2 |step: 80 |loss: tensor(6.2703e-05)
epoch 2, loss: 0.000232


In [63]:
dense = net.l1
print(true_w, dense.weight)
print(true_b, dense.bias)

[2, -3.4] Parameter containing:
tensor([[ 2.0001, -3.3999]], requires_grad=True)
4.2 Parameter containing:
tensor([4.2000], requires_grad=True)
