In [1]:
import torch
import torch.nn

In [2]:
y = torch.randn(3)
y

tensor([ 0.1197, -0.1563, -0.0108])

In [4]:
y_hat = torch.randn((3,1))
y_hat.size()

torch.Size([3, 1])

In [5]:
loss = (y_hat - y.view(y_hat.size())) ** 2 / 2
loss

tensor([[0.1319],
        [0.0971],
        [0.1821]])

In [18]:
#A选项
lossA = (y_hat.view(-1) - y) ** 2 / 2
print(lossA)
#C选项
lossC = (y_hat - y.view(y_hat.shape)) ** 2 / 2
print(lossC)
#D选项
lossD = (y_hat - y.view(-1, 1)) ** 2 / 2
print(lossD)

tensor([0.1319, 0.0971, 0.1821])
tensor([[0.1319],
        [0.0971],
        [0.1821]])
tensor([[0.1319],
        [0.0971],
        [0.1821]])
